Submission service2
kir-dev/startlap-sch pull request #70
Opened 2023-06-29 12:11 UTC by MBarni458

Submission service (and controller) with error messages

2023-07-02 22:45 UTC, DannySS123 requested changes
Nice work!
I left comments, for some small problems.
Please rebase this branch to master and format the files (with the .vscode folder in the master, a simple save on the files will do it)

If you need help, just let us know.

2023-07-02 22:45 UTC, DannySS123 commented on packages/backend/src/submissions/submissions.service.ts
> +    }
if the error is not a prisma error then simply throw it

2023-07-02 22:45 UTC, DannySS123 commented on packages/backend/src/submissions/submissions.service.ts
> +    }
if the error is not a prisma error then simply throw it

2023-07-02 22:45 UTC, DannySS123 commented on packages/backend/src/submissions/submissions.controller.ts
> +  create(@Body() data: SubmissionEntitiy) {
CreateSubmissionDto

2023-07-02 22:45 UTC, DannySS123 commented on packages/backend/src/submissions/dto/create-submission.dto.ts
> +export class CreateSubmissionDto extends PartialType(SubmissionEntitiy) {}
This works, but making everything optional isn't the best solution.
For example we won't need the id, check the link dtos for help.

2023-08-13 15:02 UTC, Tschonti requested changes
Getting there, just a few things I found
I merged master into your branch and fixed the conflicts, and also ran prettier.
Let me know if you have any questions about the requested changes.

2023-08-13 15:02 UTC, Tschonti commented on packages/backend/src/submissions/dto/create-submission.dto.ts
> +export class CreateSubmissionDto extends OmitType(SubmissionEntitiy, ['id']) {}
OmitType should be imported from `@nestjs/swagger`, otherwise it won't show up right in swagger

2023-08-13 15:02 UTC, Tschonti commented on packages/backend/src/submissions/dto/update-submission.dto.ts
> +export class UpdateSubmissionDto extends PartialType(SubmissionEntitiy) {}
PartialType should be imported from `@nestjs/swagger`, otherwise it won't show up right in swagger

Also, the update dto should extend the Create dto, so the id field won't be on the request body (it's sent in the url)

2023-08-13 15:02 UTC, Tschonti commented on packages/backend/src/submissions/entities/submission.entity.ts
> +  oldLinkId: string
oldLinkId should be optional. If the user wants to submit a new link, this field will be empty.

This has to be marked with `@IsOptional` to class-validator, and a `?` to typescript

2023-08-13 15:02 UTC, Tschonti commented on packages/backend/src/submissions/submissions.service.ts
> +    }
This handles the violation of the unique constraint correctly, but another Prisma error can occur.
If you submit a submission with an `oldLinkId` that doesn't exist in the `Link` table, the foreign key constraint will be violated. I believe the code of that error is `P2003`, it should be handled the same way as `P2002`

2023-08-13 15:02 UTC, Tschonti commented on packages/backend/src/submissions/submissions.service.ts
> +    }
same as the create method

2023-08-21 16:35 UTC, Tschonti commented
Since the main functionality is done and this PR is blocking other features, I'm merging this. The unresolved conversations should be fixed separately, ideally by the original author, I've created #84 for that

2023-08-21 16:39 UTC, merged