Feature/51 trace link visits
kir-dev/startlap-sch pull request #75
Opened 2023-07-24 23:16 UTC by Dkrisztan

Closes #51

2023-07-24 23:23 UTC, Dkrisztan commented
The endpoint @Tschonti wrote `GET /links/{slug}` would not work (as far as I'm concerned) because there is already and endpoint with `links/:id`, so I created the `links/visit/:slug` endpoint. I accidentally pushed the removal of the previous migrations (they might cause problems for others too I suppose). The redirect and the insertion of the timestamp + linkId works fine although I think the timestamp is not correct.

2023-07-25 07:01 UTC, Tschonti requested changes
Nice job! Just gave a few suggestions so that you follow our conventions better.

Also, I think it would be better to merge the `visit` and `getUrlFromSlug` methods of the `LinkSerice` into one.  Because this way, we're querying the same link twice and we don't do anything with the result of the first method. So the new method would find the link by the slug, throw an error if it's not found, then create the `Visit`, then return with the url.

2023-07-25 07:01 UTC, Tschonti commented on packages/backend/prisma/schema.prisma
> +model Visits {
very nitpicky, but the other table names are not in plural, so this should be just Visit as well

2023-07-25 07:01 UTC, Tschonti commented on packages/backend/src/links/dto/visit.dto.ts
> +}
Again, just Visit, and also class names should start with a capital letter

2023-07-25 07:01 UTC, Tschonti commented on packages/backend/src/links/links.service.ts
> +          timeStamp: new Date().toISOString(),
Since you've added a default value to this field in the schema, you don't have to provide a value here, prisma or psql will fill it for you with the current timestamp

2023-07-25 07:01 UTC, Tschonti commented on packages/backend/src/links/links.service.ts
> +      throw new BadRequestException('The slug you entered is not found!')
This is rather a NotFoundException

2023-07-27 20:09 UTC, Tschonti approved these changes
Perfect 👌

Do you think we will need the test endpoint later on? If not, remove that before merging

2023-07-27 21:25 UTC, Dkrisztan commented
>

2023-07-27 21:27 UTC, Dkrisztan commented
The test endpoint won't be needed, I'll leave it in until the next meeting just in case so we can test it together

2023-08-01 09:11 UTC, Tschonti commented
This will be merged in #78

2023-08-01 09:11 UTC, closed without merging