Navbar
kir-dev/startlap-sch pull request #87
Opened 2023-09-20 20:22 UTC by balintking

2023-09-22 18:08 UTC, DannySS123 requested changes
Szép munka, jól néz ki 👌 💯 

Pár apróságot találtam, azokat javítsd kérlek.
A navigation-menu.tsx elég durva lett, de működik úgyhogy nekem jó lesz.
Van pár merge conflict, azokat is jó lenne feloldani.

@berenteb reviewját is várjuk meg, aztán mehet is be.

Hajrá, csak így tovább 🔥

2023-09-22 18:08 UTC, DannySS123 commented on packages/client/src/app/page.tsx
> +      <Navbar></Navbar>
< Navbar />

2023-09-22 18:08 UTC, DannySS123 commented on packages/client/src/components/ui/searchbar.tsx
> +    </>
<></> nem kell, mivel csak egy elem van benne

2023-09-22 18:08 UTC, DannySS123 commented on packages/client/src/components/navbar/navbar.tsx
> +    </header>
Ezek a kommentek is nagyon szépen mutatják, hogy ezeket a részeket ki lehetne szedni külön file-okba, komponensekbe.

2023-09-22 18:08 UTC, DannySS123 commented on packages/client/src/components/ui/navigation-menu.tsx
> +    {children}{" "}
{" "} általában mentés utáni formázáskor szokott odakerülni amikor ottmarad egy felesleges space, nem tudom hogy ez most szándékos-e, de tippre nem :D

2024-01-30 19:26 UTC, DannySS123 approved these changes
Niice, pár merge conflict, azon kívül szerintem jó lesz 👌 
Tailwind configokról kérdezzük meg @berenteb -t hogy melyik maradjon

2024-01-30 19:40 UTC, balintking commented
Rendben, rebaseltem mainre, remélem nem szúrtam el semmit.

2024-02-03 16:43 UTC, Tschonti commented
Lehet valamit elrontottam a cleanup közben, mert amiket Dani kért, azok nem mind lettek megoldva

2024-02-05 18:53 UTC, balintking commented
Amire emlékeztem, változtatásokat megcsináltam. Lehet mergelni, vagy még a configok miatt várjunk?

2024-02-05 20:07 UTC, Tschonti commented
most nincs érdemi változás a tailwind.configon, szóval szerintem mehet. De majd egyszer meséld el, mit csinál a `navigation-menu.tsx` fájl 😅

2024-02-05 20:37 UTC, merged