Collection authentication and authorization
kir-dev/startlap-sch pull request #94
Opened 2023-11-30 16:47 UTC by MBarni458

Solution for: #91

2023-12-01 19:24 UTC, DannySS123 reviewed
Nice, a [collection.controller.ts](https://github.com/kir-dev/startlap-sch/pull/94/files#diff-683a5d0b9b658fe4ceeeb954d8c8917d01e031f055adf79e66d21fdc9f24a91c) ben a függvények között lehetnek üres sorok? :D

2023-12-02 16:10 UTC, Tschonti requested changes
Szép munka, egyetlen mini "hibát" találtam.

A migrációs fájlok hiányoznak, de az nem is baj, úgyis mindig összeakadnak. Ha ez bement, akkor elvileg már nem nagyon fog kelleni más sémamódosítás, majd én felpusholom a végleges verziót létrehozó migrációt.

2023-12-02 16:10 UTC, Tschonti commented on packages/backend/src/collection/collection.service.ts
> +      throw new ForbiddenException("You don't have permission to edit this resource")
replace edit with delete

2023-12-05 15:50 UTC, Tschonti approved these changes
🚀

2023-12-05 17:57 UTC, merged